Ported to use reusable sequence parser for uint
davidfowl/Channels pull request #157
Opened 2016-11-04 23:15 UTC by KrzysztofCwalina

2016-11-07 17:41 UTC, davidfowl requested changes

2016-11-07 17:41 UTC, davidfowl commented on src/Channels/ReadableBuffer.cs
> +        int? ISequence<ReadOnlyMemory<byte>>.Length => _length >= 0 ? _length : (int?)null;
Shouldn't it compute the length?

2016-11-07 17:41 UTC, davidfowl commented on test/Channels.Tests/project.json
> +    "System.Collections.Sequences": "0.1.0-e161104-6"
Use 0.1.0-*

2016-11-07 17:41 UTC, davidfowl commented on src/Channels.Text.Primitives/ReadableBufferExtensions.cs
> +            if(!buffer.TryParseUInt32(out value, out consumed)){
nit: Fix the brace formatting 😄

2016-11-07 17:48 UTC, KrzysztofCwalina commented on src/Channels/ReadableBuffer.cs
> +        int? ISequence<ReadOnlyMemory<byte>>.Length => _length >= 0 ? _length : (int?)null;
the point of int? is that if the collection has the length it returns it; if it does not, then the consumer can compute it.

2016-11-07 18:27 UTC, KrzysztofCwalina commented on test/Channels.Tests/project.json
> +    "System.Collections.Sequences": "0.1.0-e161104-6"
fixed

2016-11-07 18:27 UTC, KrzysztofCwalina commented on src/Channels.Text.Primitives/ReadableBufferExtensions.cs
> +            if(!buffer.TryParseUInt32(out value, out consumed)){
fixed

2016-11-08 00:21 UTC, davidfowl commented on src/Channels/ReadableBuffer.cs
> +        int? ISequence<ReadOnlyMemory<byte>>.Length => _length >= 0 ? _length : (int?)null;
So lazy length = not having a length? It's just lazy....

2016-11-08 00:23 UTC, KrzysztofCwalina commented on src/Channels/ReadableBuffer.cs
> +        int? ISequence<ReadOnlyMemory<byte>>.Length => _length >= 0 ? _length : (int?)null;
Ah, makes sense. I missed that.

2016-11-08 00:42 UTC, davidfowl approved these changes

2016-11-08 01:02 UTC, davidfowl approved these changes

2016-11-08 01:02 UTC, merged