Support cursor-relative operations (and add intellisense to ReadCursor)
davidfowl/Channels pull request #97
Opened 2016-09-22 10:07 UTC by mgravell

Allows:

    var cursor2 = cursor1 + 17;

and

    int delta = cursor2 - cursor1; // 17

2016-09-22 10:12 UTC, Drawaes commented
Good work, very useful "book marking" by taking a cursor is much more useful now!

2016-09-22 10:53 UTC, mgravell commented
Note refactored this to use `Seek`, but IMO the deleted implementation in `+` (see commit history) is cleaner and easier to grok; *might* be worth considering resurrecting that and making it the master? Although would need to respect the existing Seek semantic of stopping at the end rather than throwing

2016-09-23 06:54 UTC, davidfowl commented on src/Channels/ReadCursor.cs
> +            while(segment != null)
nit: formatting (ctrl + k, ctrl + d)

2016-09-23 06:55 UTC, davidfowl requested changes
Do you think these operations are useful when you can't really get cursors outside of slices?

2016-09-23 06:59 UTC, mgravell commented
Yes, in particular subtraction for asking about lengths between two points
("how much got written?"). The addition is semantically cleaner than
`Slice(...).Start` if you need to talk about pos+n.

On 23 Sep 2016 7:56 a.m., "David Fowler" <notifications@github.com> wrote:

> *@davidfowl* requested changes on this pull request.
>
> Do you think these operations are useful when you can't really get cursors
> outside of slices?
> ------------------------------
>
> In src/Channels/ReadCursor.cs
> <https://github.com/davidfowl/Channels/pull/97#pullrequestreview-1279382>:
>
> > +            {
> +                throw new ArgumentOutOfRangeException(nameof(bytes));
> +            }
> +            return result;
> +        }
> +
> +        /// <summary>
> +        /// Calcualte the offset between two cursors
> +        /// </summary>
> +        /// <remarks>The first operand must be equal or greater than the second operand -
> +        /// meaning: the expected result must be non-negative</remarks>
> +        public static int operator -(ReadCursor later, ReadCursor earlier)
> +        {
> +            var segment = earlier.Segment;
> +            int index = earlier.Index, delta = 0;
> +            while(segment != null)
>
> nit: formatting (ctrl + k, ctrl + d)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davidfowl/Channels/pull/97#pullrequestreview-1279382>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABDsHQgc28in2mZspsE28cDdjvCTa54ks5qs3gAgaJpZM4KDuXM>
> .
>

2016-09-23 07:37 UTC, davidfowl commented on test/Channels.Tests/ReadCursorFacts.cs
> +                        if (i == 30) System.Diagnostics.Debugger.Break();
Remove debugger.break

2016-09-23 07:37 UTC, davidfowl commented on test/Channels.Tests/ReadCursorFacts.cs
> +                        throw new Exception($"Failed for {nameof(i)}={i}: {ex.Message}", ex);
wut?

2016-09-23 07:37 UTC, davidfowl requested changes

2018-03-01 09:10 UTC, closed without merging