Managed sockets: Perform zero-length socket reads while waiting for incoming data
davidfowl/Channels pull request #98
Opened 2016-09-23 08:42 UTC by mgravell

2016-09-23 18:22 UTC, davidfowl requested changes

2016-09-23 18:22 UTC, davidfowl commented on src/Channels.Networking.Sockets/SocketConnection.cs
> +                        initialDataBuffer = Interlocked.Exchange(ref _recycledSmallBuffer, null) ?? new byte[SmallBufferBytes];
You should detect windows and use 0 byte buffers, otherwise use this trick.

2016-09-23 18:22 UTC, davidfowl commented on src/Channels.Networking.Sockets/SocketConnection.cs
> +                            buffer.Ensure(1); // ask for *something*, then use whatever is available (usually much much more)
You can leave out 1, that's the default.

2016-09-23 21:50 UTC, mgravell commented on src/Channels.Networking.Sockets/SocketConnection.cs
> +                            buffer.Ensure(1); // ask for *something*, then use whatever is available (usually much much more)
Addressed: 9d23721

2016-09-23 21:50 UTC, mgravell commented on src/Channels.Networking.Sockets/SocketConnection.cs
> +                        initialDataBuffer = Interlocked.Exchange(ref _recycledSmallBuffer, null) ?? new byte[SmallBufferBytes];
Addressed: 2cd2f19

2016-09-29 01:10 UTC, davidfowl approved these changes

2016-09-29 01:12 UTC, merged